// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW_IXntvCGkfdhkoUzZQPSJwcztCekcPE',
    appId: '1:278837395335:web:1345597e52598f6ff35d22',
    messagingSenderId: '278837395335',
    projectId: 'todolistapp-33065',
    authDomain: 'todolistapp-33065.firebaseapp.com',
    storageBucket: 'todolistapp-33065.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb8lHDZE9VPrPE86OgGeOW0TKZiqgx6NI',
    appId: '1:278837395335:android:46f70bbd43b4495ff35d22',
    messagingSenderId: '278837395335',
    projectId: 'todolistapp-33065',
    storageBucket: 'todolistapp-33065.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4k-JWzCgYuu_oT5frbTfC466nQxBESGQ',
    appId: '1:278837395335:ios:afebd4468e2ccceff35d22',
    messagingSenderId: '278837395335',
    projectId: 'todolistapp-33065',
    storageBucket: 'todolistapp-33065.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4k-JWzCgYuu_oT5frbTfC466nQxBESGQ',
    appId: '1:278837395335:ios:afebd4468e2ccceff35d22',
    messagingSenderId: '278837395335',
    projectId: 'todolistapp-33065',
    storageBucket: 'todolistapp-33065.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW_IXntvCGkfdhkoUzZQPSJwcztCekcPE',
    appId: '1:278837395335:web:59b0a56f2fbac520f35d22',
    messagingSenderId: '278837395335',
    projectId: 'todolistapp-33065',
    authDomain: 'todolistapp-33065.firebaseapp.com',
    storageBucket: 'todolistapp-33065.appspot.com',
  );
}
